apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 6
  template:
    metadata:
      name: ngnix-pod
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-container
          image: nginx