apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      name: ngnix-pod-2
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-container-2
          image: nginx